version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
<<<<<<< HEAD
      - "${REDIS_PORT}:6379"  
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data 
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf",
      "--requirepass", "${REDIS_PASSWORD}"
    ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
=======
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data 
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
>>>>>>> origin/feature/User-Management

  bridge:
    build: ./bridge
    container_name: bridge
    depends_on:
      - redis
    environment:
<<<<<<< HEAD
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
=======
      - REDIS_HOST=redis
      - REDIS_PORT=6379
>>>>>>> origin/feature/User-Management
