version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"  
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data 
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf",
      "--requirepass", "${REDIS_PASSWORD}",
       "--bind", "0.0.0.0"
    ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  bridge:
    build: ./bridge
    container_name: bridge
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
